// src/wc/components/Tag/Tag.tsx
import { Component, Prop, Event, EventEmitter, h, Host } from '@stencil/core';

export type TagIntent     = 'neutral' | 'brand' | 'ai' | 'negative' | 'warning' | 'caution' | 'positive';
export type TagContrast   = 'strong' | 'bold' | 'medium' | 'faint';
export type TagElevation  = 'none' | 'flat' | 'elevated';
export type TagSize       = 'md' | 'sm' | 'xs';
export type TagBackground = 'faint' | 'medium' | 'bold' | 'strong' | 'always-dark';

const TEXT_VARIANT: Record<TagSize, string> = {
  md: 'text-body-medium',
  sm: 'text-body-small',
  xs: 'text-caption',
};

const ICON_SIZE: Record<TagSize, number> = { md: 20, sm: 16, xs: 12 };

@Component({
  tag: 'ds-tag',
  styleUrl: 'Tag.css',
  scoped: true,
})
export class Tag {
  @Prop() label!: string;
  @Prop() intent: TagIntent = 'neutral';
  @Prop() contrast: TagContrast = 'faint';
  @Prop() elevation: TagElevation = 'none';
  @Prop() size: TagSize = 'md';
  @Prop() rounded: boolean = false;
  @Prop() removable: boolean = false;
  @Prop() maxWidth: string | number | undefined;
  @Prop() inactive: boolean = false;
  @Prop() background: TagBackground | undefined;
  @Prop({ mutable: true }) pressed: boolean = false;
  /** Whether the tag has a click/toggle behavior. */
  @Prop() interactive: boolean = false;

  /** Fired when the remove button is clicked. */
  @Event() dsRemove!: EventEmitter<void>;
  /** Fired when an interactive tag is clicked. */
  @Event() dsClick!: EventEmitter<void>;
  /** Fired when the pressed state toggles. */
  @Event() dsPressedChange!: EventEmitter<boolean>;

  private handleClick = () => {
    if (this.inactive) return;
    this.pressed = !this.pressed;
    this.dsPressedChange.emit(this.pressed);
    this.dsClick.emit();
  };

  private handleKeyDown = (e: KeyboardEvent) => {
    if (this.inactive) return;
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      this.handleClick();
    }
  };

  private handleRemove = (e: MouseEvent) => {
    e.stopPropagation();
    this.dsRemove.emit();
  };

  render() {
    const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
    const sz = this.size.toUpperCase() as 'MD' | 'SM' | 'XS';
    const hasIconSlot = true; // always render slot, consumer decides whether to fill it
    const textVariant = TEXT_VARIANT[this.size];
    const iconSize = ICON_SIZE[this.size];

    const maxWidthStyle = this.maxWidth != null
      ? { maxWidth: typeof this.maxWidth === 'number' ? `${this.maxWidth}px` : this.maxWidth }
      : undefined;

    const hostCls: Record<string, boolean> = {
      'tag': true,
      [`tag--intent-${this.intent}`]: true,
      [`tag--contrast-${this.contrast}`]: true,
      [`tag--elevation-${this.elevation}`]: true,
      [`tag--size-${this.size}`]: true,
      'tag--rounded': this.rounded,
      'tag--rounded-no-icon-left': this.rounded, // consumer overrides via slot presence hack
      'tag--rounded-no-remove-right': this.rounded && !this.removable,
      [`tag--icon-left-${sz}`]: false, // toggled by slotchange
      [`tag--icon-right-${sz}`]: this.removable,
      'tag--removable': this.removable,
      'tag--interactive': this.interactive,
      'tag--inactive': this.inactive,
      'tag--pressed': this.pressed,
      'tag--on-medium':      this.background === 'medium',
      'tag--on-bold':        this.background === 'bold',
      'tag--on-strong':      this.background === 'strong',
      'tag--on-always-dark': this.background === 'always-dark',
    };

    return (
      <Host
        class={hostCls}
        style={maxWidthStyle}
        onClick={this.interactive ? this.handleClick : undefined}
        onKeyDown={this.interactive ? this.handleKeyDown : undefined}
        role={this.interactive ? 'button' : undefined}
        tabIndex={this.interactive ? (this.inactive ? -1 : 0) : undefined}
        aria-pressed={this.interactive && this.pressed !== undefined ? String(this.pressed) : undefined}
        aria-disabled={this.inactive || undefined}
      >
        {/* Leading icon slot — consumer provides an icon element */}
        <span class="tag__icon-slot" style={{ fontSize: `${iconSize}px`, lineHeight: '0' }}>
          <slot name="icon" />
        </span>
        {/* Label */}
        <span class={{ 'tag__label': true, [textVariant]: true }}>
          {this.label}
        </span>
        {/* Remove button */}
        {this.removable && (
          <button
            type="button"
            class="tag__remove"
            onClick={this.handleRemove}
            aria-label={`Remove ${this.label}`}
            tabIndex={-1}
          >
            {/* Remove icon slot — defaults to × glyph */}
            <slot name="remove-icon">
              <span class="tag__remove-x" style={{ fontSize: `${iconSize}px`, lineHeight: '0' }}>
                ✕
              </span>
            </slot>
          </button>
        )}
      </Host>
    );
  }
}

// src/components/Tag/Tag.tsx
import React, { forwardRef } from 'react';
import { cn } from '@/utils/cn';
import { Text } from '@/components/Text';
import { LabelWrap } from '@/components/LabelWrap';
import { CrossUI } from '@ds-mo/icons';
import type { IconComponent } from '@/types/icons';
import styles from './Tag.module.css';

export type TagIntent    = 'neutral' | 'brand' | 'ai' | 'negative' | 'warning' | 'caution' | 'positive';
export type TagContrast  = 'strong' | 'bold' | 'medium' | 'faint';
export type TagElevation = 'none' | 'flat' | 'elevated';
export type TagSize      = 'md' | 'sm' | 'xs';

export interface TagProps {
  label: string;
  intent?: TagIntent;
  contrast?: TagContrast;
  /**
   * Visual chrome level.
   *   none     — filled with intent bg, no border, no shadow  [default]
   *   flat     — transparent bg + intent-coloured border ring
   *   elevated — filled with intent bg + elevated shadow
   */
  elevation?: TagElevation;
  size?: TagSize;
  rounded?: boolean;
  /** Leading icon component. */
  icon?: IconComponent;
  removable?: boolean;
  onRemove?: () => void;
  /** Override the default CrossUI remove icon. */
  removeIcon?: IconComponent;
  maxWidth?: string | number;
  inactive?: boolean;
  /** Makes the tag clickable. Pair with pressed/onPressedChange for filter-chip behaviour. */
  onClick?: () => void;
  pressed?: boolean;
  onPressedChange?: (pressed: boolean) => void;
  className?: string;
}

const ICON_SIZE: Record<TagSize, number> = { md: 20, sm: 16, xs: 12 };

const TEXT_STYLE_MAP: Record<TagSize, string> = {
  md: 'text-body-medium',
  sm: 'text-body-small',
  xs: 'text-caption',
};

export const Tag = forwardRef<HTMLDivElement, TagProps>(
  (
    {
      label,
      intent    = 'neutral',
      contrast  = 'faint',
      elevation = 'none',
      size      = 'md',
      rounded   = false,
      icon: Icon,
      removable = false,
      onRemove,
      removeIcon: RemoveIcon,
      maxWidth,
      inactive  = false,
      onClick,
      pressed,
      onPressedChange,
      className,
    },
    ref
  ) => {
    const isInteractive  = !!onClick || !!onPressedChange;
    const hasRemove      = removable && !!onRemove;
    const iconSize       = ICON_SIZE[size];
    const textStyle      = TEXT_STYLE_MAP[size];
    const elevKey        = elevation.charAt(0).toUpperCase() + elevation.slice(1);
    const sizeKey        = size.toUpperCase() as 'MD' | 'SM' | 'XS';

    const classes = cn(
      styles.tag,
      styles[`intent${intent.charAt(0).toUpperCase() + intent.slice(1)}`],
      styles[`contrast${contrast.charAt(0).toUpperCase() + contrast.slice(1)}`],
      styles[`elevation${elevKey}`],
      styles[`size${size.charAt(0).toUpperCase() + size.slice(1)}`],
      rounded    && styles.rounded,
      // Pill padding correction — extra space-050 on bare sides (no content anchor)
      rounded && !Icon      && (styles as Record<string, string>)[`roundedLeft${sizeKey}`],
      rounded && !hasRemove && (styles as Record<string, string>)[`roundedRight${sizeKey}`],
      removable  && styles.removable,
      isInteractive && styles.interactive,
      inactive   && styles.inactive,
      pressed    && styles.pressed,
      className,
    );

    const style = maxWidth != null
      ? { maxWidth: typeof maxWidth === 'number' ? `${maxWidth}px` : maxWidth }
      : undefined;

    const handleInteract = isInteractive && !inactive
      ? () => {
          onPressedChange?.(!pressed);
          onClick?.();
        }
      : undefined;

    const handleKeyDown = isInteractive && !inactive
      ? (e: React.KeyboardEvent<HTMLDivElement>) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            onPressedChange?.(!pressed);
            onClick?.();
          }
        }
      : undefined;

    return (
      <div
        ref={ref}
        className={classes}
        style={style}
        onClick={handleInteract}
        onKeyDown={handleKeyDown}
        role={isInteractive ? 'button' : undefined}
        tabIndex={isInteractive && !inactive ? 0 : undefined}
        aria-pressed={onPressedChange != null ? pressed : undefined}
        aria-disabled={inactive || undefined}
      >
        {Icon && <Icon size={iconSize} />}
        <LabelWrap size={size}>
          <Text variant={textStyle as never} as="span" color="inherit">
            {label}
          </Text>
        </LabelWrap>
        {removable && onRemove && (
          <button
            type="button"
            className={styles.removeButton}
            onClick={(e) => { e.stopPropagation(); onRemove(); }}
            aria-label={`Remove ${label}`}
            tabIndex={-1}
          >
            {RemoveIcon ? <RemoveIcon size={iconSize} /> : <CrossUI size={iconSize} />}
          </button>
        )}
      </div>
    );
  }
);

Tag.displayName = 'Tag';
