// src/components/LabelWrap/LabelWrap.tsx
import React from 'react';
import { cn } from '@/utils/cn';
import styles from './LabelWrap.module.css';

interface LabelWrapProps {
  children: React.ReactNode;
  /**
   * Maps to typography size — controls optical horizontal padding:
   *   xs  → 2px (caption scale)
   *   sm | md | lg → 4px (body scale, default)
   */
  size?: 'xs' | 'sm' | 'md' | 'lg';
  /** Enables truncation with ellipsis — use inside full-width containers. */
  truncate?: boolean;
  className?: string;
}

/**
 * Internal utility wrapper used inside interactive components (Button, Tag,
 * Input, Select, MenuItem, etc.) to:
 *   1. Kill the inherited line-height strut from body { line-height: 1.5 }
 *   2. Add optical horizontal padding around the text
 *
 * Not exported from the public barrel — internal use only.
 */
export const LabelWrap = ({ children, size = 'md', truncate = false, className }: LabelWrapProps) => (
  <span className={cn(styles.labelWrap, size === 'xs' && styles.sizeXs, truncate && styles.truncate, className)}>
    {children}
  </span>
);

LabelWrap.displayName = 'LabelWrap';

// src/wc/components/LabelWrap/LabelWrap.tsx
import { Component, Prop, h, Host } from '@stencil/core';

export type LabelWrapSize = 'xs' | 'sm' | 'md' | 'lg';

/**
 * Internal utility wrapper that kills line-height struts and adds optical
 * horizontal padding. Used inside interactive components (Button, Tag, etc.)
 *
 * Not intended as a standalone consumer-facing component — internal use only.
 */
@Component({
  tag: 'ds-label-wrap',
  styleUrl: 'LabelWrap.css',
  scoped: true,
})
export class LabelWrap {
  /** Typography size — controls optical horizontal padding. */
  @Prop() size: LabelWrapSize = 'md';

  /** Enable truncation with ellipsis — use inside full-width containers. */
  @Prop() truncate: boolean = false;

  render() {
    return (
      <Host
        class={{
          'label-wrap': true,
          'size-xs': this.size === 'xs',
          'size-sm': this.size === 'sm',
          'size-lg': this.size === 'lg',
          truncate: this.truncate,
        }}
      >
        <slot />
      </Host>
    );
  }
}
