// src/wc/components/Loader/Loader.tsx
import { Component, Prop, h } from '@stencil/core';

@Component({
  tag: 'ds-loader',
  styleUrl: 'Loader.css',
  shadow: true,
})
export class Loader {
  /** Render size in px. Designed on a 16×16 viewBox; stroke scales proportionally. */
  @Prop() size: number = 20;
  /**
   * Accessible label for standalone usage. Wraps the spinner in a live region
   * and renders the label visually-hidden. Omit when the host element already
   * conveys busy state via aria-busy.
   */
  @Prop() label: string | undefined;

  render() {
    const px = `${this.size}px`;
    const svg = (
      <svg
        style={{ width: px, height: px }}
        viewBox="0 0 16 16"
        fill="none"
        class="spinner"
        aria-hidden="true"
      >
        <circle
          cx="8" cy="8" r="5"
          stroke="currentColor"
          stroke-width="1"
          stroke-linecap="round"
          stroke-dasharray="23.6 7.9"
        />
      </svg>
    );

    if (!this.label) return svg;

    return (
      <span role="status" aria-live="polite" class="status">
        {svg}
        <span class="visually-hidden">{this.label}</span>
      </span>
    );
  }
}

// src/components/Loader/Loader.tsx
import React from 'react';
import styles from './Loader.module.css';

export interface LoaderProps {
  /**
   * Render size in px. Designed at 16px (r=6, strokeWidth=1).
   * Stroke weight scales proportionally with size — same behaviour as icons.
   * Defaults to 20.
   */
  size?: number;
  className?: string;
  /**
   * Accessible label announced by assistive tech when the Loader is used
   * standalone. When provided, the spinner is wrapped in a live region
   * (`role="status"`, `aria-live="polite"`) and the label is rendered
   * visually-hidden so screen readers announce it on mount.
   *
   * Omit when the Loader is rendered inside a host that already conveys
   * busy state (e.g. a Button with `aria-busy`) — the spinner stays
   * `aria-hidden` to avoid double-announcing.
   */
  label?: string;
}

/**
 * Placeholder spinner component. Will be replaced with a full Loader
 * component once motion/brand specs are finalised.
 *
 * Designed at 16×16 viewBox so it matches the icon grid:
 *   - r=5  → 10px circle in a 16px box (3px optical padding each side)
 *   - strokeWidth=1 at native size → scales to 1.25px at 20px, 1.5px at 24px
 */
export const Loader = ({ size = 20, className, label }: LoaderProps) => {
  const svg = (
    <svg
      width={size}
      height={size}
      viewBox="0 0 16 16"
      fill="none"
      className={`${styles.loader}${className ? ` ${className}` : ''}`}
      aria-hidden="true"
    >
      <circle
        cx="8"
        cy="8"
        r="5"
        stroke="currentColor"
        strokeWidth="1"
        strokeLinecap="round"
        strokeDasharray="23.6 7.9"
      />
    </svg>
  );

  if (label === undefined) return svg;

  return (
    <span role="status" aria-live="polite" className={styles.status}>
      {svg}
      <span className={styles.visuallyHidden}>{label}</span>
    </span>
  );
};

Loader.displayName = 'Loader';
