// src/wc/components/Button/Button.tsx
import { Component, Prop, Event, EventEmitter, Element, State, h, Host } from '@stencil/core';

export type ButtonVariant   = 'primary' | 'secondary';
export type ButtonElevation = 'none' | 'flat' | 'elevated' | 'floating';
export type ButtonIntent    = 'none' | 'neutral' | 'brand' | 'ai' | 'negative' | 'warning' | 'caution' | 'positive';
export type ButtonSize      = 'xs' | 'sm' | 'md' | 'lg';
export type ButtonContrast  = 'strong' | 'bold' | 'medium' | 'faint';
export type ButtonBackground = 'faint' | 'medium' | 'bold' | 'strong' | 'always-dark';

const ICON_SIZE: Record<ButtonSize, number> = { xs: 12, sm: 16, md: 20, lg: 24 };
const TEXT_CLASS: Record<ButtonSize, string> = {
  xs: 'text-caption-emphasis',
  sm: 'text-body-small-emphasis',
  md: 'text-body-medium-emphasis',
  lg: 'text-body-large-emphasis',
};

@Component({
  tag: 'ds-button',
  styleUrl: 'Button.css',
  scoped: true,
})
export class Button {
  @Element() el!: HTMLElement;

  @Prop() variant: ButtonVariant = 'primary';
  @Prop() intent: ButtonIntent = 'brand';
  @Prop() size: ButtonSize = 'md';
  @Prop() label: string | undefined;
  @Prop() rounded: boolean = false;
  @Prop() fullWidth: boolean = false;
  @Prop() width: string | undefined;
  @Prop() contrast: ButtonContrast = 'bold';
  @Prop() background: ButtonBackground | undefined;
  @Prop() dropdown: boolean = false;
  @Prop() badgeCount: number | undefined;
  @Prop() elevation: ButtonElevation | undefined;
  @Prop() loading: boolean = false;
  @Prop() inactive: boolean = false;
  @Prop() href: string | undefined;
  @Prop() target: string | undefined;
  @Prop() type: 'button' | 'submit' | 'reset' = 'button';
  @Prop({ attribute: 'aria-label' }) ariaLabel: string | undefined;
  @Prop({ attribute: 'aria-labelledby' }) ariaLabelledby: string | undefined;

  @State() private hasIcon: boolean = false;

  @Event() dsClick!: EventEmitter<MouseEvent>;
  @Event() dsMouseEnter!: EventEmitter<MouseEvent>;
  @Event() dsMouseLeave!: EventEmitter<MouseEvent>;

  componentWillLoad() {
    this.hasIcon = !!this.el.querySelector('[slot="icon"]');
  }

  private handleClick = (e: MouseEvent) => {
    if (this.inactive || this.loading) return;
    this.dsClick.emit(e);
  };

  private get effectiveElevation(): ButtonElevation {
    return this.elevation ?? (this.variant === 'primary' ? 'none' : 'flat');
  }

  render() {
    const Tag = this.href ? 'a' : 'button';
    const size = this.size;
    const iconSize = ICON_SIZE[size];
    const textClass = TEXT_CLASS[size];
    const elev = this.effectiveElevation;
    const hasLabel = !!this.label;
    const showLeading = this.hasIcon || this.loading;
    const isIconOnly = showLeading && !hasLabel;
    const isLabelOnly = hasLabel && !showLeading;
    const isIconAndLabel = showLeading && hasLabel;
    const bg = this.background;

    const btnCls: Record<string, boolean> = {
      btn: true,
      [this.variant]: true,
      [`intent${cap(this.intent)}`]: true,
      [`size${size.toUpperCase()}`]: size !== 'md',
      rounded: this.rounded,
      inactive: this.inactive || this.loading,
      iconOnly: isIconOnly,
      labelOnly: isLabelOnly,
      iconAndLabel: isIconAndLabel,
      dropdown: this.dropdown,
      [`contrast${cap(this.contrast)}`]: this.variant === 'primary' && this.intent !== 'none' && this.contrast !== 'bold',
      [`elevation${cap(elev)}`]: true,
      onMedium: bg === 'medium',
      onBold: bg === 'bold',
      onStrong: bg === 'strong',
      onAlwaysDark: bg === 'always-dark',
      fullWidth: this.fullWidth,
    };

    const extraProps: Record<string, unknown> = {};
    if (Tag === 'button') {
      extraProps.type = this.type;
      extraProps.disabled = this.inactive || this.loading;
    }
    if (this.href) extraProps.href = this.href;
    if (this.target) extraProps.target = this.target;

    return (
      <Host class={{ 'btn-host': true, 'btn-host--full': this.fullWidth }}>
        <Tag
          class={btnCls}
          style={this.width ? { width: this.width } : undefined}
          aria-label={this.ariaLabel}
          aria-labelledby={this.ariaLabelledby}
          aria-disabled={this.inactive || this.loading || undefined}
          aria-busy={this.loading || undefined}
          onClick={this.handleClick}
          onMouseEnter={(e: MouseEvent) => !this.inactive && !this.loading && this.dsMouseEnter.emit(e)}
          onMouseLeave={(e: MouseEvent) => !this.inactive && !this.loading && this.dsMouseLeave.emit(e)}
          {...extraProps}
        >
          {/* Leading icon / loader */}
          <span class="btn__icon" style={{ fontSize: `${iconSize}px`, display: showLeading ? undefined : 'none' }}>
            {this.loading
              ? <ds-loader size={iconSize} />
              : <slot name="icon" />
            }
          </span>
          {/* Label */}
          {hasLabel && (
            <span class={`btn__label ${textClass}`}>{this.label}</span>
          )}
          {/* Trailing chevron */}
          {this.dropdown && (
            <svg
              class="btn__chevron"
              width={iconSize}
              height={iconSize}
              viewBox="0 0 20 20"
              fill="none"
              aria-hidden="true"
            >
              <path d="M5 7.5L10 12.5L15 7.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
          )}
          {/* Badge */}
          {this.badgeCount != null && this.badgeCount > 0 && (
            <span class="btn__badge">
              {this.badgeCount > 9 ? '+' : this.badgeCount}
            </span>
          )}
        </Tag>
      </Host>
    );
  }
}

function cap(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// src/components/Button/Button.tsx
import React, { forwardRef } from 'react';
import { cn } from '@/utils/cn';
import { Text } from '@/components/Text';
import { LabelWrap } from '@/components/LabelWrap';
import { Loader } from '@/components/Loader';
import { ChevronDown } from '@ds-mo/icons';
import type { IconComponent } from '@/types/icons';
import styles from './Button.module.css';

export type ButtonVariant  = 'primary' | 'secondary';
export type ButtonElevation = 'none' | 'flat' | 'elevated' | 'floating';
export type ButtonIntent   = 'none' | 'neutral' | 'brand' | 'ai' | 'negative' | 'warning' | 'caution' | 'positive';
export type ButtonSize     = 'xs' | 'sm' | 'md' | 'lg';
export type ButtonContrast = 'strong' | 'bold' | 'medium' | 'faint';

export interface ButtonProps {
  /** Polymorphic element type. Defaults to 'button'. */
  as?: React.ElementType;
  /** Visual variant. Defaults to 'primary'. */
  variant?: ButtonVariant;
  /** Label text. */
  label?: string;
  /** Leading icon component from @ds-mo/icons. */
  icon?: IconComponent;
  /** Semantic intent. Defaults to 'brand'. */
  intent?: ButtonIntent;
  /** Size. Defaults to 'md'. */
  size?: ButtonSize;
  /** Pill shape with extra padding. */
  rounded?: boolean;
  /** Fill container width. Label truncates if space is tight. */
  fullWidth?: boolean;
  /** Fixed width. Omit for content width. */
  width?: React.CSSProperties['width'];
  /** Contrast level (primary variant only). Defaults to 'bold'. */
  contrast?: ButtonContrast;
  /** Show trailing ChevronDown dropdown indicator. */
  dropdown?: boolean;
  /** Badge count. */
  badgeCount?: number;
  /**
   * Chrome level for secondary; shadow level for primary.
   *   none     — ghost (transparent, no border, no shadow)
   *   flat     — border only, transparent bg  [default for secondary]
   *   elevated — bg-primary + shadow          [default for primary]
   *   floating — bg-primary + FAB-strength shadow
   */
  elevation?: ButtonElevation;
  /** Show loading spinner in place of icon. Prevents interaction. */
  loading?: boolean;

  onClick?: (e: React.MouseEvent<HTMLElement>) => void;
  onMouseEnter?: React.MouseEventHandler<HTMLElement>;
  onMouseLeave?: React.MouseEventHandler<HTMLElement>;
  className?: string;
  inactive?: boolean;
  type?: 'button' | 'submit' | 'reset';
  id?: string;
  'aria-label'?: string;
  href?: string;
  target?: string;
  rel?: string;
}

const ICON_SIZE_MAP: Record<ButtonSize, number> = { xs: 12, sm: 16, md: 20, lg: 24 };

const TEXT_STYLE_MAP: Record<ButtonSize, string> = {
  xs: 'text-caption-emphasis',
  sm: 'text-body-small-emphasis',
  md: 'text-body-medium-emphasis',
  lg: 'text-body-large-emphasis',
};


export const Button = forwardRef<HTMLElement, ButtonProps>(
  (
    {
      as,
      variant = 'primary',
      label,
      icon: Icon,
      intent = 'brand',
      size = 'md',
      rounded = false,
      fullWidth = false,
      width,
      contrast = 'bold',
      dropdown = false,
      badgeCount,
      elevation,
      loading = false,
      onClick,
      onMouseEnter,
      onMouseLeave,
      className,
      inactive = false,
      type = 'button',
      id,
      'aria-label': ariaLabel,
      href,
      target,
      rel,
    },
    ref
  ) => {
    const Component = (as ?? 'button') as React.ElementType;
    const isButton = !as || as === 'button';
    const isInteractive = !inactive && !loading;

    const hasIcon = !!Icon;
    const hasLabel = !!label;
    const showLeading = hasIcon || loading; // spinner fills the icon slot
    const isIconOnly = showLeading && !hasLabel;
    const isLabelOnly = hasLabel && !showLeading;
    const isIconAndLabel = showLeading && hasLabel;
    const iconSize = ICON_SIZE_MAP[size];
    const textStyle = TEXT_STYLE_MAP[size];

    // Derive default elevation per variant: primary→none, secondary→flat
    const effectiveElevation: ButtonElevation = elevation ?? (variant === 'primary' ? 'none' : 'flat');
    const elevKey = effectiveElevation.charAt(0).toUpperCase() + effectiveElevation.slice(1);

    const classes = cn(
      styles.button,
      styles[variant],
      styles[`intent${intent.charAt(0).toUpperCase() + intent.slice(1)}`],
      size !== 'md' && styles[`size${size.toUpperCase()}`],
      rounded && styles.rounded,
      (inactive || loading) && styles.inactive,
      isIconOnly && styles.iconOnly,
      isLabelOnly && styles.labelOnly,
      isIconAndLabel && styles.iconAndLabel,
      dropdown && styles.dropdown,
      variant === 'primary' && intent !== 'none' && contrast !== 'bold' && styles[`contrast${contrast.charAt(0).toUpperCase() + contrast.slice(1)}`],
      styles[`elevation${elevKey}`],
      fullWidth && styles.fullWidth,
      className,
    );

    const resolvedAriaLabel = ariaLabel || label || 'button';

    const extraProps: Record<string, unknown> = {};
    if (isButton) {
      extraProps.type = type;
      extraProps.disabled = inactive || loading;
    }
    if (href) extraProps.href = href;
    if (target) extraProps.target = target;
    if (rel) extraProps.rel = rel;

    return (
      <Component
        ref={ref}
        id={id}
        className={classes}
        style={width ? { width } : undefined}
        onClick={isInteractive ? onClick : undefined}
        onMouseEnter={isInteractive ? onMouseEnter : undefined}
        onMouseLeave={isInteractive ? onMouseLeave : undefined}
        aria-label={resolvedAriaLabel}
        aria-busy={loading || undefined}
        {...extraProps}
      >
        {loading ? (
          <Loader size={iconSize} />
        ) : (
          Icon && <Icon size={iconSize} />
        )}
        {label && (
          <LabelWrap truncate={fullWidth}>
            <Text variant={textStyle as never} as="span" color="inherit">
              {label}
            </Text>
          </LabelWrap>
        )}
        {dropdown && <ChevronDown size={iconSize} />}
        {badgeCount != null && badgeCount > 0 && (
          <span className={styles.badge}>{badgeCount > 9 ? '+' : badgeCount}</span>
        )}
      </Component>
    );
  }
);

Button.displayName = 'Button';
