// src/components/ButtonGroup/ButtonGroup.tsx
import React from 'react';
import { cn } from '@/utils/cn';
import styles from './ButtonGroup.module.css';

export interface ButtonGroupProps {
  children: React.ReactNode;
  className?: string;
}

/**
 * Renders Button children flush side-by-side with a 1px divider between them.
 * Outer corners keep the button's own border-radius; inner corners are flattened.
 *
 * Individual button chrome (shadow/border) is suppressed — the group container
 * carries the elevation so it wraps the whole control as one visual unit.
 *
 * Divider behaviour by variant:
 *   secondary / primary+none — full-height color-border-tertiary line
 *   primary (with intent)    — color-border-tertiary-on-{contrast}-background
 *   ghost (secondary+none)   — short centred line (icon/text height)
 *
 * Rounded groups: outer edges keep pill padding; inner edges revert to base padding.
 * Mix of intents is only valid when variant="secondary"; primary groups must be
 * homogeneous (same intent + contrast on all items).
 */
export const ButtonGroup = ({ children, className }: ButtonGroupProps) => {
  const items = React.Children.toArray(children).filter(React.isValidElement);
  const count = items.length;

  // Read elevation + rounded from first child to drive the group container style.
  const firstEl    = items[0] as React.ReactElement<Record<string, unknown>> | undefined;
  const firstProps = firstEl?.props as { variant?: string; elevation?: string; rounded?: boolean } | undefined;
  const firstVariant    = firstProps?.variant ?? 'secondary';
  const firstElevation  = firstProps?.elevation ?? (firstVariant === 'primary' ? 'none' : 'flat');
  const groupRounded    = !!firstProps?.rounded;
  const groupElevKey    = firstElevation.charAt(0).toUpperCase() + firstElevation.slice(1);

  return (
    <div
      className={cn(
        styles.group,
        (styles as Record<string, string>)[`group${groupElevKey}`],
        groupRounded && styles.groupRounded,
        className,
      )}
      role="group"
    >
      {items.map((child, i) => {
        const el = child as React.ReactElement<Record<string, unknown>>;
        const p = el.props as {
          className?: string;
          variant?: string;
          elevation?: string;
          size?: string;
          intent?: string;
          contrast?: string;
          rounded?: boolean;
          icon?: unknown;
          label?: unknown;
        };

        const isFirst = i === 0;
        const isLast  = i === count - 1;
        const isMid   = !isFirst && !isLast;

        const variant    = p.variant  ?? 'secondary';
        const size       = (p.size    ?? 'md') as 'xs' | 'sm' | 'md' | 'lg';
        const contrast   = p.contrast ?? 'bold';
        const intent     = p.intent   ?? 'brand';
        const isRounded  = !!p.rounded;
        const isIconOnly = !!p.icon && !p.label;
        // Ghost: secondary button with elevation='none' (replaces old tertiary variant)
        const isGhost    = variant === 'secondary' && (p.elevation ?? 'flat') === 'none';
        const isPrimary  = variant === 'primary' && intent !== 'none';

        // Contrast class suffix — capitalised first letter
        const contrastKey = contrast.charAt(0).toUpperCase() + contrast.slice(1);

        // Size suffix for rounded padding correction — uppercase
        // XS rounded has no extra padding in Button so needs no correction
        const sizeKey = size.toUpperCase() as 'MD' | 'SM' | 'LG' | 'XS';
        const needsRoundedCorrection = isRounded && !isIconOnly && size !== 'xs';

        // Divider injected as a separate element so it's never affected by
        // the adjacent button's opacity (e.g. disabled state).
        const dividerClasses = cn(
          styles.divider,
          isGhost && styles.dividerGhost,
          isGhost && size === 'xs' && styles.dividerGhostXS,
          isGhost && size === 'sm' && styles.dividerGhostSM,
          isGhost && size === 'lg' && styles.dividerGhostLG,
          isPrimary && (styles as Record<string, string>)[`divider${contrastKey}`],
        );

        return (
          <React.Fragment key={i}>
            {i > 0 && <div className={dividerClasses} aria-hidden="true" />}
            {React.cloneElement(el, {
              className: cn(
                p.className,
                styles.item,
                isFirst && styles.first,
                isLast  && styles.last,
                isMid   && styles.middle,

                // Ghost (secondary+elevation=none): ::after overlay gets 4px radius treatment
                isGhost && styles.itemShort,

                // Rounded: revert inner-edge padding to base (non-pill) value
                needsRoundedCorrection && isFirst && (styles as Record<string, string>)[`roundedFirst${sizeKey}`],
                needsRoundedCorrection && isLast  && (styles as Record<string, string>)[`roundedLast${sizeKey}`],
                needsRoundedCorrection && isMid   && (styles as Record<string, string>)[`roundedMid${sizeKey}`],
              ),
            })}
          </React.Fragment>
        );
      })}
    </div>
  );
};

ButtonGroup.displayName = 'ButtonGroup';

// src/wc/components/ButtonGroup/ButtonGroup.tsx
import { Component, Prop, Event, EventEmitter, h, Host } from '@stencil/core';

export type ButtonGroupElevation = 'none' | 'flat' | 'elevated' | 'floating';
export type ButtonGroupSize      = 'xs' | 'sm' | 'md' | 'lg';

export interface ButtonGroupItem {
  label?: string;
  /** Icon name for <ds-icon>. Set via JS property. */
  icon?: string;
  variant?: 'primary' | 'secondary';
  intent?: 'none' | 'neutral' | 'brand' | 'negative' | 'warning' | 'positive';
  inactive?: boolean;
  href?: string;
}

@Component({
  tag: 'ds-button-group',
  styleUrl: 'ButtonGroup.css',
  scoped: true,
})
export class ButtonGroup {
  /**
   * Array of button descriptors. Set via JS property.
   * @example el.items = [{ label: 'Filter', icon: 'Filter' }, { label: 'Sort' }];
   */
  @Prop() items: ButtonGroupItem[] = [];

  /** Chrome level for the group container. */
  @Prop() elevation: ButtonGroupElevation = 'flat';

  /** Size passed to each ds-button. */
  @Prop() size: ButtonGroupSize = 'md';

  /** Pill shape for group + buttons. */
  @Prop() rounded: boolean = false;

  /** Emits the index of the clicked item. */
  @Event() dsClick!: EventEmitter<number>;

  render() {
    const items = this.items;
    const count = items.length;
    const elev = this.elevation;
    const elevKey = elev.charAt(0).toUpperCase() + elev.slice(1);
    const isGhost = elev === 'none';

    const groupCls: Record<string, boolean> = {
      group: true,
      [`group${elevKey}`]: true,
      groupRounded: this.rounded,
    };

    return (
      <Host>
        <div class={groupCls} role="group">
          {items.map((item, i) => {
            const isFirst = i === 0;
            const isLast = i === count - 1;
            const isMid = !isFirst && !isLast;
            const variant = item.variant ?? 'secondary';
            const isIconOnly = !!item.icon && !item.label;
            const needsRoundedCorrection = this.rounded && !isIconOnly && this.size !== 'xs';
            const sizeKey = this.size.toUpperCase() as 'MD' | 'SM' | 'LG' | 'XS';

            const itemCls: Record<string, boolean> = {
              item: true,
              first: isFirst,
              last: isLast,
              middle: isMid,
              itemShort: isGhost && variant === 'secondary',
              [`roundedFirst${sizeKey}`]: !!(needsRoundedCorrection && isFirst),
              [`roundedLast${sizeKey}`]: !!(needsRoundedCorrection && isLast),
              [`roundedMid${sizeKey}`]: !!(needsRoundedCorrection && isMid),
            };

            const dividerCls: Record<string, boolean> = {
              divider: true,
              dividerGhost: isGhost,
              dividerGhostXS: isGhost && this.size === 'xs',
              dividerGhostSM: isGhost && this.size === 'sm',
              dividerGhostLG: isGhost && this.size === 'lg',
            };

            return [
              i > 0 && (
                <div class={dividerCls} aria-hidden="true" />
              ),
              <ds-button
                class={itemCls}
                variant={variant}
                intent={item.intent ?? 'none'}
                elevation={elev}
                size={this.size}
                label={item.label}
                rounded={this.rounded}
                inactive={item.inactive}
                href={item.href}
                onDsClick={() => this.dsClick.emit(i)}
              >
                {item.icon && (
                  <ds-icon slot="icon" name={item.icon} />
                )}
              </ds-button>,
            ];
          })}
        </div>
      </Host>
    );
  }
}
