// src/components/Slider/Slider.tsx
import React, { forwardRef, useCallback, useEffect, useId, useRef, useState } from 'react';
import { cn } from '@/utils/cn';
import { Text } from '@/components/Text';
import styles from './Slider.module.css';

export interface SliderProps {
  value: number;
  onChange: (value: number) => void;
  min?: number;
  max?: number;
  step?: number;
  label: string;
  id?: string;
  inactive?: boolean;
  className?: string;
}

export const Slider = forwardRef<HTMLDivElement, SliderProps>(
  ({ value, onChange, min = 0, max = 100, step = 1, label, id: idProp, inactive = false, className }, ref) => {
    const generatedId = useId();
    const id = idProp ?? generatedId;
    const containerRef = useRef<HTMLDivElement>(null);
    const [pct, setPct] = useState(() => {
      const range = max - min;
      return range === 0 ? 0 : Math.round(((value - min) / range) * 100);
    });

    const sync = useCallback(() => {
      const range = max - min;
      setPct(range === 0 ? 0 : Math.round(((value - min) / range) * 100));
    }, [value, min, max]);

    useEffect(() => { sync(); }, [sync]);

    const handleInput = (e: React.ChangeEvent<HTMLInputElement>) => {
      onChange(Number(e.target.value));
    };

    return (
      <div ref={ref} className={cn(styles.field, className)}>
        <div className={styles.labelRow}>
          <Text variant="text-body-small-emphasis" as="label" htmlFor={id}>{label}</Text>
          <Text variant="text-body-small-emphasis" as="span">{value}</Text>
        </div>
        <div
          ref={containerRef}
          className={cn(styles.track, inactive && styles.trackInactive, pct === 0 && styles.trackAtMin)}
          style={{ '--slider-pct': pct } as React.CSSProperties}
        >
          <div className={styles.trackInner}>
            <div className={styles.fillTrack}><div className={styles.fill} /></div>
            <div className={styles.thumb} />
          </div>
          <input
            type="range"
            id={id}
            min={min}
            max={max}
            step={step}
            value={value}
            onChange={handleInput}
            disabled={inactive}
            className={styles.input}
            aria-valuemin={min}
            aria-valuemax={max}
            aria-valuenow={value}
          />
        </div>
      </div>
    );
  }
);

Slider.displayName = 'Slider';

// src/wc/components/Slider/Slider.tsx
import { Component, Prop, Event, EventEmitter, h, Host } from '@stencil/core';

let idCounter = 0;

@Component({
  tag: 'ds-slider',
  styleUrl: 'Slider.css',
  scoped: true,
})
export class Slider {
  private generatedId = `ds-slider-${++idCounter}`;

  @Prop() value: number = 0;
  @Prop() min: number = 0;
  @Prop() max: number = 100;
  @Prop() step: number = 1;
  @Prop() label!: string;
  @Prop() isInactive: boolean = false;
  @Prop() valueText: string | undefined;
  /** Associates with an external <label>. Defaults to an auto-generated ID. */
  @Prop() inputId: string | undefined;

  @Event() dsChange!: EventEmitter<number>;

  private handleInput = (e: Event) => {
    this.dsChange.emit(Number((e.target as HTMLInputElement).value));
  };

  private get pct() {
    const range = this.max - this.min;
    return range === 0 ? 0 : Math.round(((this.value - this.min) / range) * 100);
  }

  render() {
    const finalId = this.inputId ?? this.generatedId;
    const pct = this.pct;

    return (
      <Host class="field">
        <div class="label-row">
          <ds-text as="label" variant="text-body-small" emphasis for={finalId}>
            {this.label}
          </ds-text>
          <ds-text as="span" variant="text-body-small" emphasis>
            {this.value}
          </ds-text>
        </div>
        <div
          class={{
            track: true,
            'ds-control-inactive': this.isInactive,
            'track--at-min': pct === 0,
          }}
          style={{ '--slider-pct': String(pct) } as Record<string, string>}
        >
          <div class="track-inner">
            <div class="fill-track"><div class="fill" /></div>
            <div class="thumb" />
          </div>
          <input
            type="range"
            id={finalId}
            min={this.min}
            max={this.max}
            step={this.step}
            value={this.value}
            disabled={this.isInactive}
            class="range-input"
            aria-valuetext={this.valueText}
            onInput={this.handleInput}
          />
        </div>
      </Host>
    );
  }
}
