// src/wc/components/Checkbox/Checkbox.tsx
import { Component, Prop, Event, EventEmitter, h, Host } from '@stencil/core';

let idCounter = 0;

@Component({
  tag: 'ds-checkbox',
  styleUrl: 'Checkbox.css',
  scoped: true,
})
export class Checkbox {
  private labelId = `ds-checkbox-label-${++idCounter}`;

  @Prop() label!: string;
  @Prop({ mutable: true }) checked: boolean = false;
  @Prop() indeterminate: boolean = false;
  @Prop() inactive: boolean = false;

  @Event() dsChange!: EventEmitter<boolean>;

  private handleActivate = () => {
    if (this.inactive) return;
    this.checked = !this.checked;
    this.dsChange.emit(this.checked);
  };

  private handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === ' ' || e.key === 'Enter') {
      e.preventDefault();
      this.handleActivate();
    }
  };

  render() {
    const isMarked = this.checked || this.indeterminate;

    return (
      <Host
        role="checkbox"
        aria-checked={this.indeterminate ? 'mixed' : String(this.checked)}
        aria-disabled={this.inactive || undefined}
        aria-labelledby={this.labelId}
        tabIndex={this.inactive ? -1 : 0}
        class={{ checkbox: true, inactive: this.inactive }}
        onClick={this.handleActivate}
        onKeyDown={this.handleKeyDown}
      >
        <span class={{ box: true, 'box--marked': isMarked }}>
          {isMarked && (
            <span class="checkmark" aria-hidden="true">
              {this.indeterminate ? '−' : '✓'}
            </span>
          )}
        </span>
        <span id={this.labelId} class="text-body-medium checkbox__label">
          {this.label}
        </span>
      </Host>
    );
  }
}

// src/components/Checkbox/Checkbox.tsx
import React, { forwardRef, useId } from 'react';
import { cn } from '@/utils/cn';
import { Text } from '@/components/Text';
import type { IconComponent } from '@/types/icons';
import styles from './Checkbox.module.css';

export interface CheckboxProps {
  label: string;
  checked?: boolean;
  indeterminate?: boolean;
  onChange?: (checked: boolean) => void;
  inactive?: boolean;
  className?: string;
  /** Icon for checked state. */
  checkedIcon?: IconComponent;
  /** Icon for unchecked state. */
  uncheckedIcon?: IconComponent;
  /** Icon for indeterminate state. */
  indeterminateIcon?: IconComponent;
}

export const Checkbox = forwardRef<HTMLDivElement, CheckboxProps>(
  (
    {
      label,
      checked = false,
      indeterminate = false,
      onChange,
      inactive = false,
      className,
      checkedIcon: CheckedIcon,
      uncheckedIcon: UncheckedIcon,
      indeterminateIcon: IndeterminateIcon,
    },
    ref
  ) => {
    const labelId = useId();
    const handleClick = () => {
      if (!inactive) onChange?.(!checked);
    };

    const iconColor = indeterminate || checked ? 'var(--color-foreground-primary)' : 'var(--color-foreground-secondary)';
    const Icon = indeterminate ? IndeterminateIcon : checked ? CheckedIcon : UncheckedIcon;

    return (
      <div
        ref={ref}
        role="checkbox"
        aria-checked={indeterminate ? 'mixed' : checked}
        aria-disabled={inactive || undefined}
        aria-labelledby={labelId}
        data-inactive={inactive || undefined}
        tabIndex={inactive ? -1 : 0}
        className={cn(styles.checkbox, inactive && styles.inactive, className)}
        onClick={handleClick}
        onKeyDown={e => { if (e.key === ' ' || e.key === 'Enter') { e.preventDefault(); handleClick(); } }}
      >
        {Icon ? <Icon size={20} color={iconColor} /> : (
          <span className={cn(styles.box, (checked || indeterminate) && styles.boxChecked)}>
            {(checked || indeterminate) && <span className={styles.checkmark}>{indeterminate ? '−' : '✓'}</span>}
          </span>
        )}
        <Text id={labelId} variant="text-body-medium" as="span" color="inherit">
          {label}
        </Text>
      </div>
    );
  }
);

Checkbox.displayName = 'Checkbox';
