// src/wc/components/ToggleButtonGroup/ToggleButtonGroup.tsx
import { Component, Prop, Event, EventEmitter, h, Host } from '@stencil/core';

export type ToggleGroupElevation  = 'none' | 'flat' | 'elevated' | 'floating';
export type ToggleGroupSize       = 'md' | 'sm' | 'xs';
export type ToggleGroupBackground = 'faint' | 'medium' | 'bold' | 'strong' | 'always-dark';

export interface ToggleGroupItem {
  id: string;
  label?: string;
  /** Icon name for <ds-icon>. */
  icon?: string;
  inactive?: boolean;
}

@Component({
  tag: 'ds-toggle-button-group',
  styleUrl: 'ToggleButtonGroup.css',
  scoped: true,
})
export class ToggleButtonGroup {
  /**
   * Array of item descriptors. Set via JS property.
   * @example el.items = [{ id: 'list', label: 'List' }, { id: 'grid', icon: 'GridView' }];
   */
  @Prop() items: ToggleGroupItem[] = [];

  /** ID of the currently selected / pressed item. */
  @Prop({ mutable: true }) value: string = '';

  /** Chrome level for the group container. */
  @Prop() elevation: ToggleGroupElevation = 'elevated';

  /** Size passed to each ds-toggle-button. */
  @Prop() size: ToggleGroupSize = 'md';

  /** Pill shape for group + buttons. */
  @Prop() rounded: boolean = false;

  /** Parent surface context. */
  @Prop() background: ToggleGroupBackground | undefined;

  /** Emits the id of the newly selected item. */
  @Event() dsChange!: EventEmitter<string>;

  private handleItemChange(id: string) {
    if (id === this.value) return;
    this.value = id;
    this.dsChange.emit(id);
  }

  render() {
    const items = this.items;
    const count = items.length;
    const elev = this.elevation;
    const elevKey = elev.charAt(0).toUpperCase() + elev.slice(1);
    const bg = this.background;
    const isGhost = elev === 'none';

    const groupCls: Record<string, boolean> = {
      group: true,
      [`group${elevKey}`]: true,
      groupRounded: this.rounded,
    };

    return (
      <Host>
        <div class={groupCls} role="group">
          {items.map((item, i) => {
            const isFirst = i === 0;
            const isLast = i === count - 1;
            const isMid = !isFirst && !isLast;
            const isPressed = item.id === this.value;
            const isIconOnly = !!item.icon && !item.label;
            const needsRoundedCorrection = this.rounded && !isIconOnly && this.size !== 'xs';
            const sizeKey = this.size.toUpperCase() as 'MD' | 'SM' | 'XS';

            const itemCls: Record<string, boolean> = {
              item: true,
              first: isFirst,
              last: isLast,
              middle: isMid,
              itemShort: isGhost,
              itemPressed: isGhost && isPressed,
              [`roundedFirst${sizeKey}`]: !!(needsRoundedCorrection && isFirst),
              [`roundedLast${sizeKey}`]: !!(needsRoundedCorrection && isLast),
              [`roundedMid${sizeKey}`]: !!(needsRoundedCorrection && isMid),
            };

            const dividerCls: Record<string, boolean> = {
              divider: true,
              dividerGhost: isGhost,
              dividerGhostXS: isGhost && this.size === 'xs',
              dividerGhostSM: isGhost && this.size === 'sm',
            };

            return [
              i > 0 && (
                <div class={dividerCls} aria-hidden="true" />
              ),
              <ds-toggle-button
                class={itemCls}
                elevation={elev}
                size={this.size}
                label={item.label}
                icon={item.icon}
                rounded={this.rounded}
                background={bg}
                pressed={isPressed}
                inactive={item.inactive}
                onDsChange={() => this.handleItemChange(item.id)}
              />,
            ];
          })}
        </div>
      </Host>
    );
  }
}

// src/components/ToggleButtonGroup/ToggleButtonGroup.tsx
import React from 'react';
import { cn } from '@/utils/cn';
import styles from './ToggleButtonGroup.module.css';

export interface ToggleButtonGroupProps {
  children: React.ReactNode;
  className?: string;
}

/**
 * Renders ToggleButton children flush side-by-side with a 1px divider between them.
 * Outer corners keep the button's own border-radius; inner corners are flattened.
 *
 * Individual button chrome (shadow/border) is suppressed — the group container
 * carries the elevation so it wraps the whole control as one visual unit.
 *
 * Divider behaviour by elevation:
 *   elevated / flat / floating — full-height color-border-tertiary line
 *   none (ghost)               — short centred line (icon/text height)
 *
 * Rounded groups: outer edges keep pill padding; inner edges revert to base padding.
 * Pressed state and onPressedChange are managed by the consumer on each ToggleButton.
 */
export const ToggleButtonGroup = ({ children, className }: ToggleButtonGroupProps) => {
  const items = React.Children.toArray(children).filter(React.isValidElement);
  const count = items.length;

  // Read elevation + rounded from first child to drive the group container style.
  const firstEl   = items[0] as React.ReactElement<Record<string, unknown>> | undefined;
  const firstProps = firstEl?.props as { elevation?: string; rounded?: boolean } | undefined;
  const groupElevation = firstProps?.elevation ?? 'elevated';
  const groupRounded   = !!firstProps?.rounded;
  const groupElevKey   = groupElevation.charAt(0).toUpperCase() + groupElevation.slice(1);

  return (
    <div
      className={cn(
        styles.group,
        (styles as Record<string, string>)[`group${groupElevKey}`],
        groupRounded && styles.groupRounded,
        className,
      )}
      role="group"
    >
      {items.map((child, i) => {
        const el = child as React.ReactElement<Record<string, unknown>>;
        const p = el.props as {
          className?: string;
          elevation?: string;
          size?: string;
          rounded?: boolean;
          pressed?: boolean;
          icon?: unknown;
          label?: unknown;
        };

        const isFirst = i === 0;
        const isLast  = i === count - 1;
        const isMid   = !isFirst && !isLast;

        const size       = (p.size ?? 'md') as 'xs' | 'sm' | 'md';
        const isRounded  = !!p.rounded;
        const isPressed  = !!p.pressed;
        const isIconOnly = !!p.icon && !p.label;
        // Ghost: elevation='none' (no chrome) → short centred divider
        const isGhost    = (p.elevation ?? 'elevated') === 'none';

        // XS rounded has no extra padding in ToggleButton so needs no correction
        const sizeKey = size.toUpperCase() as 'XS' | 'SM' | 'MD';
        const needsRoundedCorrection = isRounded && !isIconOnly && size !== 'xs';

        // Divider injected as a separate element so it's never affected by
        // the adjacent button's opacity (e.g. disabled state).
        const dividerClasses = cn(
          styles.divider,
          isGhost && styles.dividerGhost,
          isGhost && size === 'xs' && styles.dividerGhostXS,
          isGhost && size === 'sm' && styles.dividerGhostSM,
        );

        return (
          <React.Fragment key={i}>
            {i > 0 && <div className={dividerClasses} aria-hidden="true" />}
            {React.cloneElement(el, {
              className: cn(
                p.className,
                styles.item,
                isFirst && styles.first,
                isLast  && styles.last,
                isMid   && styles.middle,

                // Ghost variant: ::after overlay gets 4px radius treatment
                isGhost && styles.itemShort,

                // Ghost + pressed: selected state background chip
                isGhost && isPressed && styles.itemPressed,

                // Rounded: revert inner-edge padding to base (non-pill) value
                needsRoundedCorrection && isFirst && (styles as Record<string, string>)[`roundedFirst${sizeKey}`],
                needsRoundedCorrection && isLast  && (styles as Record<string, string>)[`roundedLast${sizeKey}`],
                needsRoundedCorrection && isMid   && (styles as Record<string, string>)[`roundedMid${sizeKey}`],
              ),
            })}
          </React.Fragment>
        );
      })}
    </div>
  );
};

ToggleButtonGroup.displayName = 'ToggleButtonGroup';
