// src/components/Accordion/Accordion.tsx
import React, { forwardRef, useState, useRef, useEffect, useCallback, useId } from 'react';
import { cn } from '@/utils/cn';
import { Text } from '@/components/Text';
import styles from './Accordion.module.css';

export interface AccordionItemData {
  id: string;
  label: string;
  content: React.ReactNode;
  inactive?: boolean;
}

export interface AccordionProps {
  /** Items to render. */
  items: AccordionItemData[];
  /** Allow multiple items open at once. When false, behaves as an accordion. */
  multiple?: boolean;
  /** Controlled: which item IDs are expanded. */
  expandedIds?: string[];
  /** Called when expansion state changes. */
  onExpandedChange?: (ids: string[]) => void;
  className?: string;
}

export const Accordion = forwardRef<HTMLDivElement, AccordionProps>(
  ({ items, multiple = false, expandedIds: controlledIds, onExpandedChange, className }, ref) => {
    const [internalIds, setInternalIds] = useState<string[]>([]);
    const expandedIds = controlledIds ?? internalIds;

    const toggle = (id: string) => {
      let next: string[];
      if (expandedIds.includes(id)) {
        next = expandedIds.filter(x => x !== id);
      } else {
        next = multiple ? [...expandedIds, id] : [id];
      }
      setInternalIds(next);
      onExpandedChange?.(next);
    };

    return (
      <div ref={ref} className={cn(styles.accordion, className)}>
        {items.map(item => (
          <AccordionItem
            key={item.id}
            label={item.label}
            isExpanded={expandedIds.includes(item.id)}
            inactive={item.inactive}
            onToggle={() => toggle(item.id)}
          >
            {item.content}
          </AccordionItem>
        ))}
      </div>
    );
  }
);

Accordion.displayName = 'Accordion';

/* ─── AccordionItem ─────────────────────────────────────────────────────────── */

export interface AccordionItemProps {
  label: string;
  children: React.ReactNode;
  isExpanded?: boolean;
  onToggle?: () => void;
  inactive?: boolean;
  className?: string;
}

export const AccordionItem = forwardRef<HTMLDivElement, AccordionItemProps>(
  ({ label, children, isExpanded = false, onToggle, inactive = false, className }, ref) => {
    const contentRef = useRef<HTMLDivElement>(null);
    const [height, setHeight] = useState<number>(0);
    const reactId = useId();
    const triggerId = `${reactId}-trigger`;
    const panelId = `${reactId}-panel`;

    const measure = useCallback(() => {
      if (contentRef.current) {
        setHeight(contentRef.current.scrollHeight);
      }
    }, []);

    useEffect(() => {
      measure();
      const el = contentRef.current;
      if (!el) return;
      const ro = new ResizeObserver(measure);
      ro.observe(el);
      return () => ro.disconnect();
    }, [measure]);

    return (
      <div ref={ref} className={cn(styles.item, inactive && styles.inactive, className)}>
        <button
          type="button"
          id={triggerId}
          className={styles.trigger}
          onClick={() => !inactive && onToggle?.()}
          aria-expanded={isExpanded}
          aria-controls={panelId}
          aria-disabled={inactive || undefined}
          tabIndex={inactive ? -1 : 0}
        >
          <Text variant="text-body-medium-emphasis" as="span" color="inherit">
            {label}
          </Text>
          <span className={cn(styles.chevron, isExpanded && styles.chevronOpen)}>
            &#x203A;
          </span>
        </button>
        <div
          id={panelId}
          role="region"
          aria-labelledby={triggerId}
          className={styles.body}
          style={{ height: isExpanded ? height : 0 }}
          aria-hidden={!isExpanded}
        >
          <div ref={contentRef} className={styles.bodyInner}>
            {children}
          </div>
        </div>
      </div>
    );
  }
);

AccordionItem.displayName = 'AccordionItem';

// src/wc/components/Accordion/Accordion.tsx
import { Component, Prop, State, Event, EventEmitter, Element, Watch, h, Host } from '@stencil/core';

export interface AccordionItemData {
  id: string;
  label: string;
  content?: string;
  inactive?: boolean;
}

let idCounter = 0;

@Component({
  tag: 'ds-accordion',
  styleUrl: 'Accordion.css',
  scoped: true,
})
export class Accordion {
  @Element() el!: HTMLElement;

  @Prop() items: AccordionItemData[] = [];
  @Prop() multiple: boolean = false;
  /** Comma-separated list of expanded item IDs for controlled mode. */
  @Prop({ mutable: true }) expandedIds: string = '';

  @State() private internalIds: string[] = [];
  @State() private heights: Record<string, number> = {};

  @Event() dsExpandedChange!: EventEmitter<string[]>;

  private instanceId = ++idCounter;
  private resizeObservers: Map<string, ResizeObserver> = new Map();

  private get activeIds(): string[] {
    if (this.expandedIds) return this.expandedIds.split(',').map(s => s.trim()).filter(Boolean);
    return this.internalIds;
  }

  componentDidLoad() {
    this.bindResizeObservers();
  }

  disconnectedCallback() {
    this.resizeObservers.forEach(ro => ro.disconnect());
    this.resizeObservers.clear();
  }

  @Watch('items')
  onItemsChange() {
    requestAnimationFrame(() => {
      this.bindResizeObservers();
      this.measureAll();
    });
  }

  private bindResizeObservers() {
    this.resizeObservers.forEach(ro => ro.disconnect());
    this.resizeObservers.clear();

    this.items.forEach(item => {
      const inner = this.el.querySelector(`[data-inner="${item.id}"]`) as HTMLElement | null;
      if (!inner) return;
      const ro = new ResizeObserver(() => {
        this.heights = { ...this.heights, [item.id]: inner.scrollHeight };
      });
      ro.observe(inner);
      this.resizeObservers.set(item.id, ro);
    });
  }

  private measureAll() {
    const next: Record<string, number> = { ...this.heights };
    this.items.forEach(item => {
      const inner = this.el.querySelector(`[data-inner="${item.id}"]`) as HTMLElement | null;
      if (inner) next[item.id] = inner.scrollHeight;
    });
    this.heights = next;
  }

  private toggle(id: string) {
    const current = this.activeIds;
    let next: string[];
    if (current.includes(id)) {
      next = current.filter(x => x !== id);
    } else {
      next = this.multiple ? [...current, id] : [id];
    }
    this.internalIds = next;
    this.dsExpandedChange.emit(next);
  }

  render() {
    const activeIds = this.activeIds;

    return (
      <Host class="accordion">
        {this.items.map(item => {
          const isExpanded = activeIds.includes(item.id);
          const triggerId = `ds-accordion-${this.instanceId}-trigger-${item.id}`;
          const panelId = `ds-accordion-${this.instanceId}-panel-${item.id}`;
          const bodyHeight = this.heights[item.id] ?? 0;

          return (
            <div
              key={item.id}
              class={{ item: true, 'item--inactive': !!item.inactive }}
            >
              <button
                type="button"
                id={triggerId}
                class="trigger"
                onClick={() => !item.inactive && this.toggle(item.id)}
                aria-expanded={isExpanded}
                aria-controls={panelId}
                aria-disabled={item.inactive || undefined}
                tabIndex={item.inactive ? -1 : 0}
              >
                <span class="text-body-medium-emphasis">{item.label}</span>
                <span
                  class={{ chevron: true, 'chevron--open': isExpanded }}
                  aria-hidden="true"
                >&#x203A;</span>
              </button>
              <div
                id={panelId}
                role="region"
                aria-labelledby={triggerId}
                class="body"
                style={{ height: isExpanded ? `${bodyHeight}px` : '0' }}
                aria-hidden={!isExpanded}
              >
                <div class="body-inner" data-inner={item.id}>
                  {item.content
                    ? <span class="text-body-medium">{item.content}</span>
                    : <slot name={item.id} />
                  }
                </div>
              </div>
            </div>
          );
        })}
      </Host>
    );
  }
}
