// src/components/Radio/Radio.tsx
import React, { forwardRef, useRef } from 'react';
import { cn } from '@/utils/cn';
import { Text } from '@/components/Text';
import styles from './Radio.module.css';

export interface RadioOption {
  label: string;
  value: string;
  inactive?: boolean;
}

export interface RadioGroupProps {
  /** Currently selected value. */
  value: string;
  /** Called when selection changes. */
  onChange: (value: string) => void;
  /** Radio options to render. */
  options: RadioOption[];
  /** Accessible name for the group. One of `aria-label` or `aria-labelledby` is required. */
  'aria-label'?: string;
  /** ID of an element labeling the group. One of `aria-label` or `aria-labelledby` is required. */
  'aria-labelledby'?: string;
  /** Layout direction. */
  direction?: 'vertical' | 'horizontal';
  /** Disables the entire group. */
  inactive?: boolean;
  className?: string;
}

export const RadioGroup = forwardRef<HTMLDivElement, RadioGroupProps>(
  (
    {
      value,
      onChange,
      options,
      'aria-label': ariaLabel,
      'aria-labelledby': ariaLabelledBy,
      direction = 'vertical',
      inactive = false,
      className,
    },
    ref
  ) => {
    if (!ariaLabel && !ariaLabelledBy) {
      const env = (globalThis as { process?: { env?: { NODE_ENV?: string } } })
        .process?.env?.NODE_ENV;
      if (env !== 'production') {
        console.warn(
          'RadioGroup: an accessible name is required. Pass either `aria-label` or `aria-labelledby`.'
        );
      }
    }

    const itemRefs = useRef<Array<HTMLDivElement | null>>([]);

    const isActive = (i: number) =>
      i >= 0 && i < options.length && !inactive && !options[i].inactive;

    const activeIndices = options.reduce<number[]>((acc, _, i) => {
      if (isActive(i)) acc.push(i);
      return acc;
    }, []);

    const selectedIdx = options.findIndex(o => o.value === value);
    const focusableIdx = isActive(selectedIdx)
      ? selectedIdx
      : (activeIndices[0] ?? -1);

    const focusAndSelect = (i: number) => {
      itemRefs.current[i]?.focus();
      if (options[i].value !== value) onChange(options[i].value);
    };

    const moveFocus = (from: number, delta: 1 | -1) => {
      if (activeIndices.length === 0) return;
      const pos = activeIndices.indexOf(from);
      // If focus somehow lands on an inactive radio, anchor at the boundary so
      // the first arrow keystroke moves to the nearest active option.
      const startPos = pos === -1 ? (delta === 1 ? -1 : 0) : pos;
      const nextPos =
        (startPos + delta + activeIndices.length) % activeIndices.length;
      focusAndSelect(activeIndices[nextPos]);
    };

    const handleKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
      const target = e.target as HTMLElement;
      const idx = itemRefs.current.findIndex(el => el === target);
      if (idx === -1) return;

      switch (e.key) {
        case 'ArrowDown':
        case 'ArrowRight':
          e.preventDefault();
          moveFocus(idx, 1);
          break;
        case 'ArrowUp':
        case 'ArrowLeft':
          e.preventDefault();
          moveFocus(idx, -1);
          break;
        case 'Home':
          e.preventDefault();
          if (activeIndices.length) focusAndSelect(activeIndices[0]);
          break;
        case 'End':
          e.preventDefault();
          if (activeIndices.length)
            focusAndSelect(activeIndices[activeIndices.length - 1]);
          break;
      }
    };

    return (
      <div
        ref={ref}
        role="radiogroup"
        aria-label={ariaLabel}
        aria-labelledby={ariaLabelledBy}
        onKeyDown={handleKeyDown}
        className={cn(
          styles.group,
          direction === 'horizontal' && styles.horizontal,
          className
        )}
      >
        {options.map((opt, i) => (
          <RadioItem
            key={opt.value}
            ref={el => {
              itemRefs.current[i] = el;
            }}
            label={opt.label}
            checked={value === opt.value}
            inactive={inactive || opt.inactive}
            tabIndex={i === focusableIdx ? 0 : -1}
            onChange={() => onChange(opt.value)}
          />
        ))}
      </div>
    );
  }
);

RadioGroup.displayName = 'RadioGroup';

/* ─── Individual Radio Item ─────────────────────────────────────────────────── */

export interface RadioItemProps {
  label: string;
  checked?: boolean;
  onChange?: () => void;
  inactive?: boolean;
  /** Roving tabindex value. RadioGroup manages this; defaults to -1 when inactive, else 0. */
  tabIndex?: number;
  className?: string;
}

export const RadioItem = forwardRef<HTMLDivElement, RadioItemProps>(
  (
    { label, checked = false, onChange, inactive = false, tabIndex, className },
    ref
  ) => {
    const handleActivate = () => {
      if (!inactive && !checked) onChange?.();
    };

    const resolvedTabIndex = tabIndex ?? (inactive ? -1 : 0);

    return (
      <div
        ref={ref}
        role="radio"
        aria-checked={checked}
        aria-disabled={inactive || undefined}
        tabIndex={resolvedTabIndex}
        className={cn(styles.radio, inactive && styles.inactive, className)}
        onClick={handleActivate}
        onKeyDown={e => {
          if (e.key === ' ' || e.key === 'Enter') {
            e.preventDefault();
            handleActivate();
          }
        }}
      >
        <span className={cn(styles.circle, checked && styles.circleChecked)}>
          {checked && <span className={styles.dot} />}
        </span>
        <Text variant="text-body-medium" as="span" color="inherit">
          {label}
        </Text>
      </div>
    );
  }
);

RadioItem.displayName = 'RadioItem';

// src/wc/components/Radio/Radio.tsx
import { AttachInternals, Component, Prop, State, Event, EventEmitter, Element, Listen, Watch, h, Host } from '@stencil/core';
import { DEFAULT_REQUIRED_MESSAGE, setRequiredValidity } from '../../utils';

export interface RadioOption {
  label: string;
  value: string;
  isInactive?: boolean;
}

export type RadioSize = 'md' | 'sm' | 'xs';

const LABEL_VARIANT: Record<RadioSize, 'text-body-medium' | 'text-body-small' | 'text-caption'> = {
  md: 'text-body-medium',
  sm: 'text-body-small',
  xs: 'text-caption',
};

@Component({
  tag: 'ds-radio',
  styleUrl: 'Radio.css',
  scoped: true,
  formAssociated: true,
})
export class Radio {
  @Element() el!: HTMLElement;
  @AttachInternals() internals!: ElementInternals;

  /** Visible choices in this one-of-many set. */
  @Prop() options: RadioOption[] = [];
  /** Selected option value. */
  @Prop({ mutable: true }) value: string = '';
  /** Visual and placement density for every option. */
  @Prop() size: RadioSize = 'md';
  /** Native form field name. */
  @Prop({ reflect: true }) name: string | undefined;
  /** Associates the radio set with a form by id when rendered outside that form. */
  @Prop({ reflect: true }) form: string | undefined;
  /** Native disabled state for the complete set. */
  @Prop({ reflect: true }) disabled: boolean = false;
  /** Require one option to be selected for form validity. */
  @Prop({ reflect: true }) required: boolean = false;
  /** Validation message used when a required set has no selection. */
  @Prop() requiredMessage: string = DEFAULT_REQUIRED_MESSAGE;
  /** Layout direction for the option set. */
  @Prop() direction: 'vertical' | 'horizontal' = 'vertical';
  /** Design-system inactive state for the complete set. */
  @Prop() isInactive: boolean = false;
  /** Accessible name when visible group labeling is unavailable. */
  @Prop({ attribute: 'aria-label' }) ariaLabel: string | null = null;
  /** Id reference for a visible group label. */
  @Prop({ attribute: 'aria-labelledby' }) ariaLabelledby: string | undefined;

  /** Emitted after user selection with the selected option value. */
  @Event() dsChange!: EventEmitter<string>;

  private initialValue = '';
  @State() private formDisabled = false;

  componentWillLoad() {
    this.initialValue = this.value;
    this.syncFormValue();
  }

  @Watch('value')
  @Watch('disabled')
  @Watch('isInactive')
  @Watch('required')
  syncFormValue() {
    const inactive = this.isInactive || this.disabled || this.formDisabled;
    this.internals.setFormValue(inactive ? null : this.value);
    const missing = this.required && !inactive && this.value.length === 0;
    setRequiredValidity(this.internals, missing, this.requiredMessage);
  }

  formDisabledCallback(disabled: boolean) {
    this.formDisabled = disabled;
    this.syncFormValue();
  }

  formResetCallback() {
    this.value = this.initialValue;
  }

  formStateRestoreCallback(state: string | File | FormData | null) {
    this.value = typeof state === 'string' ? state : '';
  }

  private get activeItems(): HTMLElement[] {
    return Array.from(this.el.querySelectorAll<HTMLElement>('[data-radio-item]:not([data-inactive])'));
  }

  @Listen('keydown')
  handleKeyDown(e: KeyboardEvent) {
    const items = this.activeItems;
    if (!items.length) return;

    const focused = items.find(item => item === document.activeElement);
    if (!focused) return;

    const idx = items.indexOf(focused);
    let next = -1;

    switch (e.key) {
      case 'ArrowDown':
      case 'ArrowRight':
        e.preventDefault();
        next = (idx + 1) % items.length;
        break;
      case 'ArrowUp':
      case 'ArrowLeft':
        e.preventDefault();
        next = (idx - 1 + items.length) % items.length;
        break;
      case 'Home':
        e.preventDefault();
        next = 0;
        break;
      case 'End':
        e.preventDefault();
        next = items.length - 1;
        break;
    }

    if (next >= 0) {
      items[next].focus();
      const nextValue = items[next].dataset['value'];
      if (nextValue && nextValue !== this.value) {
        this.value = nextValue;
        this.dsChange.emit(nextValue);
      }
    }
  }

  private selectItem(optValue: string) {
    if (this.isInactive || this.disabled || this.formDisabled) return;
    if (optValue !== this.value) {
      this.value = optValue;
      this.dsChange.emit(optValue);
    }
  }

  render() {
    const inactive = this.isInactive || this.disabled || this.formDisabled;
    const invalid = this.required && !inactive && this.value.length === 0;
    const selectedIdx = this.options.findIndex(option => option.value === this.value);
    const firstActiveIdx = this.options.findIndex(option => !inactive && !option.isInactive);
    const focusableIdx = selectedIdx >= 0 && !inactive && !this.options[selectedIdx]?.isInactive
      ? selectedIdx
      : firstActiveIdx;

    return (
      <Host
        role="radiogroup"
        aria-label={this.ariaLabel}
        aria-labelledby={this.ariaLabelledby}
        aria-required={this.required ? 'true' : undefined}
        aria-invalid={invalid ? 'true' : undefined}
        class={{
          radio: true,
          'radio--horizontal': this.direction === 'horizontal',
          [`radio--${this.size}`]: true,
        }}
      >
        {this.options.map((option, index) => {
          const isItemInactive = inactive || !!option.isInactive;
          const isChecked = option.value === this.value;
          const tabIdx = isItemInactive ? -1 : index === focusableIdx ? 0 : -1;

          return (
            <div
              key={option.value}
              role="radio"
              aria-checked={String(isChecked)}
              aria-disabled={isItemInactive ? 'true' : undefined}
              tabIndex={tabIdx}
              data-radio-item
              data-value={option.value}
              data-inactive={isItemInactive || undefined}
              class={{
                radio__item: true,
                [`ds-control--${this.size}`]: true,
                'ds-control-inactive': isItemInactive,
                'ds-focus-ring-inset': !isItemInactive,
                'ds-interaction-fill': !isItemInactive,
              }}
              onClick={() => !isItemInactive && this.selectItem(option.value)}
              onKeyDown={(e: KeyboardEvent) => {
                if ((e.key === ' ' || e.key === 'Enter') && !isItemInactive) {
                  e.preventDefault();
                  this.selectItem(option.value);
                }
              }}
            >
              <span class="radio__placement ds-interaction-fill__content" aria-hidden="true">
                <span class={{ radio__circle: true, 'radio__circle--checked': isChecked }}>
                  {isChecked && <span class="radio__dot" />}
                </span>
              </span>
              <ds-text
                class="radio__label ds-interaction-fill__content"
                as="span"
                variant={LABEL_VARIANT[this.size]}
              >
                {option.label}
              </ds-text>
            </div>
          );
        })}
      </Host>
    );
  }
}
