// src/components/Toast/Toast.tsx
import React, { forwardRef, useEffect, useState, useCallback, useRef, useSyncExternalStore } from 'react';
import ReactDOM from 'react-dom';
import { cn } from '@/utils/cn';
import { Text } from '@/components/Text';
import { Surface } from '@/components/Surface';
import type { SurfaceIntent } from '@/components/Surface';
import styles from './Toast.module.css';

/* ─── Toast Types ───────────────────────────────────────────────────────────── */

export type ToastIntent = 'neutral' | 'brand' | 'positive' | 'negative' | 'warning' | 'caution';
export type ToastPosition = 'top-center' | 'top-right' | 'bottom-center' | 'bottom-right';

export interface ToastData {
  id: string;
  message: string;
  intent?: ToastIntent;
  duration?: number;
  onDismiss?: () => void;
}

export interface ToastOptions {
  message: string;
  intent?: ToastIntent;
  /** Auto-dismiss duration in ms. 0 = no auto-dismiss. Default 4000. */
  duration?: number;
  onDismiss?: () => void;
}

/* ─── Toast Store (external, framework-agnostic) ────────────────────────────── */

let toasts: ToastData[] = [];
const listeners = new Set<() => void>();

function emit() {
  listeners.forEach(fn => fn());
}

function getSnapshot(): ToastData[] {
  return toasts;
}

function subscribe(listener: () => void) {
  listeners.add(listener);
  return () => { listeners.delete(listener); };
}

let idCounter = 0;

export const toast = {
  show(options: ToastOptions): string {
    const id = `toast-${++idCounter}`;
    toasts = [...toasts, { id, ...options }];
    emit();
    return id;
  },
  info(message: string, options?: Omit<ToastOptions, 'message'>): string {
    return toast.show({ message, intent: 'neutral', ...options });
  },
  success(message: string, options?: Omit<ToastOptions, 'message'>): string {
    return toast.show({ message, intent: 'positive', ...options });
  },
  error(message: string, options?: Omit<ToastOptions, 'message'>): string {
    return toast.show({ message, intent: 'negative', ...options });
  },
  warning(message: string, options?: Omit<ToastOptions, 'message'>): string {
    return toast.show({ message, intent: 'warning', ...options });
  },
  dismiss(id: string) {
    toasts = toasts.filter(t => t.id !== id);
    emit();
  },
  dismissAll() {
    toasts = [];
    emit();
  },
};

/* ─── useToasts hook ────────────────────────────────────────────────────────── */

export function useToasts(): ToastData[] {
  return useSyncExternalStore(subscribe, getSnapshot, getSnapshot);
}

/* ─── Single Toast ──────────────────────────────────────────────────────────── */

const INTENT_MAP: Record<ToastIntent, SurfaceIntent> = {
  neutral: 'neutral',
  brand: 'brand',
  positive: 'positive',
  negative: 'negative',
  warning: 'warning',
  caution: 'caution',
};

interface ToastItemProps {
  data: ToastData;
}

const ToastItem: React.FC<ToastItemProps> = ({ data }) => {
  const [exiting, setExiting] = useState(false);
  const timerRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const remainingRef = useRef<number>(data.duration ?? 4000);
  const startedAtRef = useRef<number>(0);
  const pausedRef = useRef<boolean>(false);

  const dismiss = useCallback(() => {
    setExiting(true);
    setTimeout(() => {
      toast.dismiss(data.id);
      data.onDismiss?.();
    }, 200);
  }, [data]);

  const clearTimer = useCallback(() => {
    if (timerRef.current) {
      clearTimeout(timerRef.current);
      timerRef.current = undefined;
    }
  }, []);

  const startTimer = useCallback((ms: number) => {
    if (ms <= 0) return;
    startedAtRef.current = Date.now();
    timerRef.current = setTimeout(dismiss, ms);
  }, [dismiss]);

  const pause = useCallback(() => {
    if (pausedRef.current || !timerRef.current) return;
    pausedRef.current = true;
    const elapsed = Date.now() - startedAtRef.current;
    remainingRef.current = Math.max(0, remainingRef.current - elapsed);
    clearTimer();
  }, [clearTimer]);

  const resume = useCallback(() => {
    if (!pausedRef.current) return;
    pausedRef.current = false;
    startTimer(remainingRef.current);
  }, [startTimer]);

  useEffect(() => {
    remainingRef.current = data.duration ?? 4000;
    pausedRef.current = false;
    startTimer(remainingRef.current);
    return clearTimer;
  }, [data.duration, startTimer, clearTimer]);

  const isNegative = data.intent === 'negative';

  return (
    <Surface
      intent={INTENT_MAP[data.intent ?? 'neutral']}
      contrast="bold"
      elevation="floating"
      radius="lg"
      className={cn(styles.toast, exiting && styles.toastExit)}
      role={isNegative ? 'alert' : 'status'}
      aria-live={isNegative ? 'assertive' : 'polite'}
      onMouseEnter={pause}
      onMouseLeave={resume}
      onFocus={pause}
      onBlur={resume}
    >
      <Text variant="text-body-medium" as="span" color="inherit">
        {data.message}
      </Text>
      <button
        type="button"
        className={styles.dismiss}
        onClick={dismiss}
        aria-label="Dismiss"
      >
        &times;
      </button>
    </Surface>
  );
};

/* ─── ToastContainer ────────────────────────────────────────────────────────── */

export interface ToastContainerProps {
  /** Where to render toasts on screen. */
  position?: ToastPosition;
}

export const ToastContainer = forwardRef<HTMLDivElement, ToastContainerProps>(
  ({ position = 'top-center' }, ref) => {
    const items = useToasts();

    if (typeof document === 'undefined') return null;

    return ReactDOM.createPortal(
      <div
        ref={ref}
        className={cn(styles.container, styles[positionClass(position)])}
        role="region"
        aria-label="Notifications"
      >
        {items.map(item => (
          <ToastItem key={item.id} data={item} />
        ))}
      </div>,
      document.body
    );
  }
);

ToastContainer.displayName = 'ToastContainer';

function positionClass(position: ToastPosition): string {
  switch (position) {
    case 'top-center': return 'topCenter';
    case 'top-right': return 'topRight';
    case 'bottom-center': return 'bottomCenter';
    case 'bottom-right': return 'bottomRight';
  }
}

// src/wc/components/Toast/Toast.tsx
import { Component, Prop, State, h, Host } from '@stencil/core';
import { subscribeToToasts, getToasts, toast as toastService, type ToastData, type ToastIntent } from './toast-service';

export type ToastPosition = 'top-center' | 'top-right' | 'bottom-center' | 'bottom-right';

const INTENT_BG: Record<ToastIntent, string> = {
  neutral:  'var(--color-background-bold-neutral)',
  brand:    'var(--color-background-bold-brand)',
  positive: 'var(--color-background-bold-positive)',
  negative: 'var(--color-background-bold-negative)',
  warning:  'var(--color-background-bold-warning)',
  caution:  'var(--color-background-bold-caution)',
};

interface ToastItemState {
  data: ToastData;
  exiting: boolean;
  timer: ReturnType<typeof setTimeout> | null;
  remaining: number;
  startedAt: number;
  paused: boolean;
}

@Component({
  tag: 'ds-toast-provider',
  styleUrl: 'Toast.css',
  scoped: true,
})
export class ToastProvider {
  @Prop() position: ToastPosition = 'top-center';

  @State() private items: ToastItemState[] = [];

  private unsubscribe: (() => void) | null = null;

  connectedCallback() {
    this.unsubscribe = subscribeToToasts(() => this.syncFromStore());
    this.syncFromStore();
  }

  disconnectedCallback() {
    this.items.forEach(item => { if (item.timer) clearTimeout(item.timer); });
    this.unsubscribe?.();
  }

  private syncFromStore() {
    const storeToasts = getToasts();
    const existingIds = new Set(this.items.map(i => i.data.id));
    const storeIds = new Set(storeToasts.map(t => t.id));

    // Remove items no longer in store (instant, no animation since dismiss() already fires animation)
    const kept = this.items.filter(i => storeIds.has(i.data.id));

    // Add new items
    const newItems: ToastItemState[] = storeToasts
      .filter(t => !existingIds.has(t.id))
      .map(data => {
        const state: ToastItemState = {
          data,
          exiting: false,
          timer: null,
          remaining: data.duration,
          startedAt: 0,
          paused: false,
        };
        if (data.duration > 0) {
          state.startedAt = Date.now();
          state.timer = setTimeout(() => this.dismissItem(data.id), data.duration);
        }
        return state;
      });

    this.items = [...kept, ...newItems];
  }

  private dismissItem(id: string) {
    this.items = this.items.map(i =>
      i.data.id === id ? { ...i, exiting: true, timer: null } : i
    );
    setTimeout(() => {
      this.items = this.items.filter(i => i.data.id !== id);
      toastService.dismiss(id);
    }, 200);
  }

  private pauseItem(id: string) {
    this.items = this.items.map(i => {
      if (i.data.id !== id || i.paused || !i.timer) return i;
      clearTimeout(i.timer);
      const elapsed = Date.now() - i.startedAt;
      return { ...i, paused: true, timer: null, remaining: Math.max(0, i.remaining - elapsed) };
    });
  }

  private resumeItem(id: string) {
    this.items = this.items.map(i => {
      if (i.data.id !== id || !i.paused || i.remaining <= 0) return i;
      const timer = setTimeout(() => this.dismissItem(id), i.remaining);
      return { ...i, paused: false, timer, startedAt: Date.now() };
    });
  }

  private getPositionStyle(): Record<string, string> {
    const base: Record<string, string> = {
      position: 'fixed',
      zIndex: '9999',
      display: 'flex',
      flexDirection: 'column',
      gap: 'var(--dimension-space-075)',
      pointerEvents: 'none',
      padding: 'var(--dimension-space-100)',
      maxWidth: '480px',
      width: '100%',
      boxSizing: 'border-box',
    };
    switch (this.position) {
      case 'top-center':
        return { ...base, top: '0', left: '50%', transform: 'translateX(-50%)', alignItems: 'center' };
      case 'top-right':
        return { ...base, top: '0', right: '0', alignItems: 'flex-end' };
      case 'bottom-center':
        return { ...base, bottom: '0', left: '50%', transform: 'translateX(-50%)', alignItems: 'center' };
      case 'bottom-right':
        return { ...base, bottom: '0', right: '0', alignItems: 'flex-end' };
    }
  }

  render() {
    return (
      <Host style={{ display: 'contents' }}>
        <div
          class="toast-container"
          role="region"
          aria-label="Notifications"
          aria-live="polite"
          style={this.getPositionStyle()}
        >
          {this.items.map(item => (
            <div
              key={item.data.id}
              class={{ toast: true, 'toast--exit': item.exiting }}
              role={item.data.intent === 'negative' ? 'alert' : 'status'}
              style={{
                backgroundColor: INTENT_BG[item.data.intent],
                borderRadius: 'var(--dimension-radius-125)',
                boxShadow: 'var(--effect-elevation-elevated-floating)',
                display: 'flex',
                alignItems: 'center',
                gap: 'var(--dimension-space-075)',
                padding: 'var(--dimension-space-075) var(--dimension-space-100)',
                minHeight: 'var(--dimension-size-400)',
                pointerEvents: 'auto',
                color: 'var(--color-foreground-on-bold-background-primary)',
                boxSizing: 'border-box',
              }}
              onMouseEnter={() => this.pauseItem(item.data.id)}
              onMouseLeave={() => this.resumeItem(item.data.id)}
            >
              <span class="text-body-medium" style={{ flex: '1' }}>{item.data.message}</span>
              <button
                type="button"
                class="toast-dismiss"
                onClick={() => this.dismissItem(item.data.id)}
                aria-label="Dismiss"
              >
                &times;
              </button>
            </div>
          ))}
        </div>
      </Host>
    );
  }
}
