// src/wc/components/Banner/Banner.tsx
import { Component, Prop, State, Event, EventEmitter, Watch, h, Host } from '@stencil/core';

export type BannerIntent =
  | 'brand' | 'positive' | 'negative' | 'warning' | 'caution'
  | 'ai' | 'neutral' | 'walkthrough' | 'guide';

export type BannerContrast = 'faint' | 'medium' | 'bold' | 'strong';

const FADE_OUT_MS = 200;
const AUTO_DISMISS_MS = 4000;

@Component({
  tag: 'ds-banner',
  styleUrl: 'Banner.css',
  scoped: true,
})
export class Banner {
  @Prop() intent: BannerIntent = 'neutral';
  @Prop() contrast: BannerContrast = 'medium';
  @Prop() message: string = '';
  /** Renders the diagonal-stripe accent bar above the body. */
  @Prop() header: boolean = false;
  /** Renders at a fixed position (centered top) and auto-dismisses after 4 s. */
  @Prop() floating: boolean = false;
  @Prop() showDismiss: boolean = false;
  @Prop() dismissLabel: string = 'Dismiss';

  @State() private closing: boolean = false;

  @Event() dsDismiss!: EventEmitter<void>;

  private dismissTimer: ReturnType<typeof setTimeout> | null = null;
  private closeTimer: ReturnType<typeof setTimeout> | null = null;

  componentDidLoad() {
    if (this.floating && this.message) this.scheduleDismiss();
  }

  @Watch('message')
  onMessageChange(newVal: string) {
    if (this.floating && newVal) {
      this.closing = false;
      this.scheduleDismiss();
    }
  }

  disconnectedCallback() {
    this.clearTimers();
  }

  private clearTimers() {
    if (this.dismissTimer) { clearTimeout(this.dismissTimer); this.dismissTimer = null; }
    if (this.closeTimer)   { clearTimeout(this.closeTimer);   this.closeTimer = null; }
  }

  private scheduleDismiss() {
    this.clearTimers();
    this.dismissTimer = setTimeout(() => {
      this.dismissTimer = null;
      this.beginClose();
    }, AUTO_DISMISS_MS);
  }

  private beginClose() {
    this.clearTimers();
    if (this.floating) {
      this.closing = true;
      this.closeTimer = setTimeout(() => {
        this.closing = false;
        this.closeTimer = null;
        this.dsDismiss.emit();
      }, FADE_OUT_MS);
    } else {
      this.dsDismiss.emit();
    }
  }

  private getContentColor(): string {
    if (this.contrast === 'bold') return 'var(--color-foreground-on-bold-background-primary)';
    const c = this.contrast === 'faint' ? 'bold' : this.contrast === 'medium' ? 'strong' : 'medium';
    return `var(--color-foreground-${c}-${this.intent})`;
  }

  private getBg(): string {
    return `var(--color-background-${this.contrast}-${this.intent})`;
  }

  private getElevation(): string {
    return this.floating
      ? 'var(--effect-elevation-elevated-floating)'
      : 'var(--effect-elevation-elevated-sm)';
  }

  render() {
    const contentColor = this.getContentColor();
    const isAssertive = this.intent === 'negative';

    const bannerEl = (
      <div
        class={{ 'banner-wrapper': true }}
        style={{ '--banner-content': contentColor } as { [key: string]: string }}
        role={isAssertive ? 'alert' : 'status'}
        aria-live={isAssertive ? undefined : 'polite'}
      >
        <div
          class="banner-surface"
          style={{
            backgroundColor: this.getBg(),
            boxShadow: this.getElevation(),
          }}
        >
          {this.header && (
            <div class="banner-header-surface">
              <div class="banner-header" />
            </div>
          )}
          <div class="banner-body">
            <span class="text-body-medium banner-message">{this.message}</span>
            {this.showDismiss && (
              <button
                type="button"
                class="banner-dismiss"
                onClick={() => this.beginClose()}
                aria-label={this.dismissLabel}
              >
                &times;
              </button>
            )}
          </div>
        </div>
      </div>
    );

    if (this.floating) {
      return (
        <Host style={{ display: 'contents' }}>
          <div class="floating-position" style={{ zIndex: '9998' }}>
            <div class={{ 'floating-toast': true, 'floating-toast--closing': this.closing }}>
              {bannerEl}
            </div>
          </div>
        </Host>
      );
    }

    return <Host style={{ display: 'contents' }}>{bannerEl}</Host>;
  }
}

// src/components/Banner/Banner.tsx
import React, { useState, useEffect, useCallback, useRef } from 'react';
import { createPortal } from 'react-dom';
import { Cross } from '@ds-mo/icons';
import { Surface } from '@/components/Surface';
import { Text } from '@/components/Text';
import { getCssTimeMs } from '@/utils/css-tokens';
import styles from './Banner.module.css';

const TOAST_DURATION_FALLBACK_MS = 4000;
const FADE_OUT_DURATION_MS = 200;

export type BannerIntent =
  | 'brand' | 'positive' | 'negative' | 'warning' | 'caution'
  | 'ai' | 'neutral' | 'walkthrough' | 'guide';

export type BannerContrast = 'faint' | 'medium' | 'bold' | 'strong';

export interface BannerProps {
  intent: BannerIntent;
  contrast: BannerContrast;
  message: string;
  header?: boolean;
  className?: string;
  floating?: boolean;
  onDismiss?: () => void;
  /** Accessible label for the dismiss button. Defaults to "Dismiss". */
  dismissLabel?: string;
}

const getContentColorVar = (intent: BannerIntent, contrast: BannerContrast): string => {
  if (contrast === 'bold') return 'var(--color-foreground-on-bold-background-primary)';
  const contentContrast = contrast === 'faint' ? 'bold' : contrast === 'medium' ? 'strong' : 'medium';
  return `var(--color-foreground-${contentContrast}-${intent})`;
};

export const Banner: React.FC<BannerProps> = ({
  intent,
  contrast,
  message,
  header = false,
  className = '',
  floating = false,
  onDismiss,
  dismissLabel = 'Dismiss',
}) => {
  const toastDurationMs = getCssTimeMs('--effect-animation-delay-long-2', TOAST_DURATION_FALLBACK_MS);
  const messageColor = getContentColorVar(intent, contrast);
  const [isClosing, setIsClosing] = useState(false);
  const dismissTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const closeTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const beginClose = useCallback(() => {
    if (dismissTimerRef.current) clearTimeout(dismissTimerRef.current);
    if (closeTimerRef.current) clearTimeout(closeTimerRef.current);
    dismissTimerRef.current = null;
    if (floating) {
      setIsClosing(true);
      closeTimerRef.current = setTimeout(() => {
        closeTimerRef.current = null;
        onDismiss?.();
      }, FADE_OUT_DURATION_MS);
    } else {
      onDismiss?.();
    }
  }, [floating, onDismiss]);

  const scheduleDismiss = useCallback(() => {
    if (dismissTimerRef.current) clearTimeout(dismissTimerRef.current);
    dismissTimerRef.current = setTimeout(() => {
      dismissTimerRef.current = null;
      beginClose();
    }, toastDurationMs);
  }, [beginClose, toastDurationMs]);

  useEffect(() => {
    if (floating && message) scheduleDismiss();
    return () => {
      if (dismissTimerRef.current) clearTimeout(dismissTimerRef.current);
      if (closeTimerRef.current) clearTimeout(closeTimerRef.current);
    };
  }, [floating, message, scheduleDismiss]);

  const isAssertive = intent === 'negative';
  const role = isAssertive ? 'alert' : 'status';
  const ariaLive = isAssertive ? undefined : 'polite';

  const content = (
    <div
      className={`${styles.bannerWrapper} ${className}`.trim()}
      style={{ '--banner-content': messageColor } as React.CSSProperties}
      role={role}
      aria-live={ariaLive}
    >
      <Surface
        elevation={floating ? 'floating' : 'elevated'}
        intent={intent}
        contrast={contrast}
        radius="sm"
        className={styles.banner}
      >
        {header && (
          <div className={styles.bannerHeaderSurface}>
            <div className={styles.bannerHeader} aria-hidden />
          </div>
        )}
        <div className={styles.bannerBody}>
          <Text variant="text-body-medium" as="span" className={styles.message}>
            {message}
          </Text>
          {onDismiss && (
            <button
              type="button"
              className={styles.dismiss}
              onClick={beginClose}
              aria-label={dismissLabel}
            >
              <Cross size={16} />
            </button>
          )}
        </div>
      </Surface>
    </div>
  );

  if (floating) {
    return createPortal(
      <div className={styles.floatingPosition} style={{ zIndex: 9998 }}>
        <div className={`${styles.floatingToast} ${isClosing ? styles.closing : ''}`}>
          {content}
        </div>
      </div>,
      document.body
    );
  }

  return content;
};

Banner.displayName = 'Banner';
